#ifndef CONFIG_H
#define CONFIG_H

#define MAX_BOIDS 1000
#define BOID_SIZE 2.5f
#define EPSILON 0.0001f

#define PANEL_WIDTH 700
#define GUI_PADDING 25.0f
#define GUI_CONTROLS_TEXT_SIZE 20
#define GUI_LABEL_TEXT_SIZE 18
#define GUI_SLIDER_HEIGHT 30.0f
#define GUI_CHECKBOX_SIZE 22.0f
#define GUI_BUTTON_HEIGHT 35.0f
#define GUI_VERTICAL_SPACING 18.0f
#define GUI_LABEL_CONTROL_SPACING 6.0f
#define GUI_SLIDER_TEXT_SIZE 16
#endif // CONFIG_H